services:
  site:
    image: ai_prompts_site
    ports:
      - 8080:8080
    volumes:
      - ./config:/config
      - ./images:/images

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD: 260203
    volumes:
      - ./data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
