port: "8080"
url : "http://localhost:8080"


db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "SiteWatchImage"
  sslmode: "disable"
  password : "260203"
  
redis:
  host: "localhost:6379"
  db: 0
